### ISSUE TITLE
cnf cannot errors instead of handling missing config

### ISSUE THREAD

**Issue by caseyjlaw** [dsa110/dsa110-issues#168]
What is the expected behavior for cnf when `get` method is used on missing config name? I am getting an error, but I thought perhaps a `None` might be returned instead.

Example:
```
from dsautils import cnf
my_cnf = cnf.Conf(use_etcd=True)
my_cnf.get('minmax_ant')
```

The bokeh ant status page fails with this error when retrieving a missing key.
```
May 24 23:24:16 lxd110h23 panel[31742]: 2022-05-24 23:24:16,826 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7f6f268cee48>: 'NoneType' object has no attribute 'decode'
May 24 23:24:16 lxd110h23 panel[31742]: File "cnf.py", line 508, in get:
May 24 23:24:16 lxd110h23 panel[31742]: return json.loads(data.decode("utf-8")) Traceback (most recent call last):
May 24 23:24:16 lxd110h23 panel[31742]:   File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 197, in run
May 24 23:24:16 lxd110h23 panel[31742]:     exec(self._code, module.__dict__)
May 24 23:24:16 lxd110h23 panel[31742]:   File "/home/ubuntu/proj/dsa110-shell/dsa110-vis/unified_dashboard.ipynb", line 28, in <module>
May 24 23:24:16 lxd110h23 panel[31742]:     "pn.extension(\"tabulator\")\n",
May 24 23:24:16 lxd110h23 panel[31742]:   File "/home/ubuntu/proj/dsa110-shell/dsa110-vis/antmon.py", line 31, in <module>
May 24 23:24:16 lxd110h23 panel[31742]:     minmax = my_cnf.get('minmax_ant') if my_cnf is not None else None
May 24 23:24:16 lxd110h23 panel[31742]:   File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/dsautils/cnf.py", line 508, in get
May 24 23:24:16 lxd110h23 panel[31742]:     return json.loads(data.decode("utf-8"))
May 24 23:24:16 lxd110h23 panel[31742]: AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by rh-codebase** [comment]
the stack trace seems incomplete. The error is on data not minmax. In any case, the function signature is:
**def get(self, ss_name: "String") -> "Dictionary"**
So an empty dictionary is a dictionary. If python3's syntax allow for:
**-> dict,None**
Then None could be used. I personally prefer the empty dictionary since it meets the type specification. I'm sure others could argue None is more idiomatic though but that may be before python's devs wised up and added signature syntax.

**Comment by caseyjlaw** [comment]
Sorry, I may not have pasted that well. Now I am a bit confused, because I thought the issue was that a missing key was not parsed by json properly within the `get` method. However, here's a test on a nonexistent key:
```
from dsautils import cnf
   ...: my_cnf = cnf.Conf(use_etcd=True)
   ...: my_cnf.get('foo')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-90a355b4e240> in <module>
      1 from dsautils import cnf
      2 my_cnf = cnf.Conf(use_etcd=True)
----> 3 my_cnf.get('foo')

~/anaconda3/envs/casa/lib/python3.6/site-packages/dsautils/cnf.py in get(self, ss_name)
    500 
    501         self.log.function('get')
--> 502         key = self.cnf_config[ss_name]
    503 
    504         if self.use_etcd:

KeyError: 'foo'
```

The `KeyError` is a good response, but that's not what I thought I saw. Maybe we'll leave this for now and see if it comes up again.
